name: maplibre_style_spec
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:
  collection: ^1.19.0
  color_models: ^1.3.3
  csslib: ^1.0.0
  intl: ^0.19.0
  geojson_vi: ^2.2.5
  rbush: ^1.1.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  analyzer: ^6.11.0
